### ISSUE TITLE
Wrong slide when return to presentation

### ISSUE THREAD

**Issue by AndreiBiziuk** [parmsam/quarto-excalidraw#2]
When you return to the presentation by pressing the '`' key again, you are not returned to the slide from which excalidraw was opened. 
It looks like it's returning to the slide before the correct one. However, if you repeat the process of opening and closing excalidraw, it returns to the correct slide.

**Comment by parmsam** [comment]
That's odd. I can't reproduce it on my laptop. Just to be consistent, I've set it to be the same timeout delay used for the button press. The example [here](https://parmsam.github.io/quarto-excalidraw/#/title-slide) should be republished.
- https://github.com/parmsam/quarto-excalidraw/blob/main/_extensions/excalidraw/excalidraw.js#L44-L73
- https://developer.mozilla.org/en-US/docs/Web/API/Window/setTimeout

**Comment by parmsam** [comment]
Let me know if that works for you. I'll do another Github release after.

**Comment by AndreiBiziuk** [comment]
Changing the delay does not help. 
But why switch the slide after hiding the excalidraw window? If I comment this line 

```javascript
// deck.slide(currentSlideIndex);
```

then seems like everything works as it should.

```javascript
      document.addEventListener('keydown', (event) => {
        if (event.key === settings.shortcut) {
          if (excalidrawContainer.style.display === 'none') {
            currentSlideIndex = deck.getState().indexh;
            excalidrawContainer.style.display = 'block';
          } else {
            excalidrawContainer.style.display = 'none';
            if (currentSlideIndex !== null) {
              setTimeout(() => {
                // deck.slide(currentSlideIndex);
              }, 100);
            }
          }
        }
      });
```

**Comment by AndreiBiziuk** [comment]
```javascript
deck.getState().indexh
```

returns index of horizontal slide, but I have vertical slides as well (slides which divided with ---), so this is the reason of wrong slide after return to presentation.

**Comment by AndreiBiziuk** [comment]
I think it is necessary to save the entire state of the presentation and restore it entirely, or not change the state at all after returning to the presentation.

```javascript
document.addEventListener('keydown', (event) => {
        if (event.key === settings.shortcut) {
          if (excalidrawContainer.style.display === 'none') {
            currentDeckState = deck.getState();
            excalidrawContainer.style.display = 'block';
          } else {
            excalidrawContainer.style.display = 'none';
            if (currentDeckState !== null) {
              setTimeout(() => {
                deck.setState(currentDeckState);
              }, 10);
            }
          }
        }
      });
```

or

```javascript
      document.addEventListener('keydown', (event) => {
        if (event.key === settings.shortcut) {
          if (excalidrawContainer.style.display === 'none') {
            excalidrawContainer.style.display = 'block';
          } else {
            excalidrawContainer.style.display = 'none';
          }
        }
      });
```

**Comment by parmsam** [comment]
Saving state and recovering it is required to ensure both the keyboard shortcut and button press can be used interchangeably. It should work now.

**Comment by AndreiBiziuk** [comment]
Yes, it's working now! Thank you )
